"""Shared executable resource limits for the provisional engine vertical."""

REFERENCE_ENCODED_BYTES = 32 * 1024 * 1024
REFERENCE_MAX_DIMENSION = 4096
REFERENCE_MAX_PIXELS = 4_194_304
PORTABLE_CUBE_ENCODED_BYTES = 16 * 1024 * 1024

DOCUMENT_MAX_ACTIVE_JOBS = 4
DOCUMENT_MAX_QUEUED_WORK_UNITS = 2 * (REFERENCE_MAX_DIMENSION + 1)
DOCUMENT_JOB_HISTORY_LIMIT = 128

FULL_RESOLUTION_BYTES_PER_PIXEL = 12
FULL_RESOLUTION_MAX_PIXELS = 262_144
FULL_RESOLUTION_MAX_OUTPUT_BYTES = (
    FULL_RESOLUTION_MAX_PIXELS * FULL_RESOLUTION_BYTES_PER_PIXEL
)
# Converting the complete bytearray to immutable bytes temporarily retains both.
FULL_RESOLUTION_MAX_SCRATCH_BYTES = FULL_RESOLUTION_MAX_OUTPUT_BYTES
FULL_RESOLUTION_RETAINED_RESULTS = 1
